<a href="https://colab.research.google.com/github/hrtywhy/Machine-Learning/blob/main/SGD%2CKNN%2CNaive_Baiyes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
import pandas as pd
df = pd.read_csv('/content/drive/My Drive/Dataset/skripsi/dos_dataset/clean_2.csv')
#df.info()
df=df.drop('Unnamed: 0.1',axis=1)
x=df.iloc[:,df.columns != 'Label']
y=df.iloc[:,-1]
print("x\n",x.info())
y = pd.DataFrame(y)
print('y\n',y.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1245798 entries, 0 to 1245797
Data columns (total 73 columns):
 #   Column                        Non-Null Count    Dtype  
---  ------                        --------------    -----  
 0   Unnamed: 0                    1245798 non-null  int64  
 1   Unnamed: 0.1.1                1245798 non-null  int64  
 2    Source IP                    1245798 non-null  int64  
 3    Source Port                  1245798 non-null  int64  
 4    Destination IP               1245798 non-null  int64  
 5    Destination Port             1245798 non-null  int64  
 6    Protocol                     1245798 non-null  int64  
 7    Flow Duration                1245798 non-null  int64  
 8    Total Fwd Packets            1245798 non-null  int64  
 9    Total Backward Packets       1245798 non-null  int64  
 10  Total Length of Fwd Packets   1245798 non-null  float64
 11   Total Length of Bwd Packets  1245798 non-null  float64
 12   Fwd Packet Length Max      

In [6]:
df.describe()

Unnamed: 0  Unnamed: 0.1.1  ...       Inbound         Label
count  1.245798e+06    1.245798e+06  ...  1.245798e+06  1.245798e+06
mean   6.228985e+05    1.074318e+05  ...  9.624289e-01  3.339989e+00
std    3.596310e+05    1.089688e+05  ...  1.901566e-01  1.832971e+00
min    0.000000e+00    0.000000e+00  ...  0.000000e+00  0.000000e+00
25%    3.114492e+05    2.503600e+04  ...  1.000000e+00  2.000000e+00
50%    6.228985e+05    7.408800e+04  ...  1.000000e+00  3.000000e+00
75%    9.343478e+05    1.462510e+05  ...  1.000000e+00  5.000000e+00
max    1.245797e+06    6.652080e+05  ...  1.000000e+00  7.000000e+00

[8 rows x 74 columns]

In [7]:
#normalizating the data
#df.iloc[:,df.columns != ' Flow Packets/s' or df.columns != 'Flow Bytes/s']
normalized_df=(df-df.mean())/df.std()
normalized_df=normalized_df.drop(' Flow Packets/s',axis=1)
normalized_df=normalized_df.drop('Flow Bytes/s',axis=1)

In [8]:
import matplotlib.pyplot as plt
import seaborn as sn
plt.figure(figsize=(100,200))
cor = normalized_df.corr()
sn.heatmap(cor, annot=True, cmap=plt.cm.Reds)
plt.show()

In [9]:
#df=df.drop('Unnamed: 0.1',axis=1)
normalized_df.head()

Unnamed: 0  Unnamed: 0.1.1   Source IP  ...   Idle Min   Inbound     Label
0   -1.732049        0.186725   -0.030358  ...  -0.181785   0.19758 -0.731047
1   -1.732046       -0.373912   -0.030358  ...  -0.181785   0.19758 -0.731047
2   -1.732043        0.213485   -0.030358  ...  -0.181785   0.19758 -0.731047
3   -1.732040        0.215559   -0.030358  ...  -0.181785   0.19758 -0.731047
4   -1.732038       -0.757481   -0.030358  ...  -0.181785   0.19758 -0.731047

[5 rows x 72 columns]

In [10]:
normalized_df=normalized_df.drop('Unnamed: 0', axis=1)
normalized_df=normalized_df.drop('Unnamed: 0.1.1', axis=1) 

In [11]:
y=pd.DataFrame(y)

In [12]:
normalized_df.describe()

Source IP   Source Port  ...       Inbound         Label
count  1.245798e+06  1.245798e+06  ...  1.245798e+06  1.245798e+06
mean  -2.874317e-13  1.054733e-12  ... -2.792804e-12 -4.782956e-12
std    1.000000e+00  1.000000e+00  ...  1.000000e+00  1.000000e+00
min   -1.919144e+01 -9.406960e-01  ... -5.061243e+00 -1.822172e+00
25%   -3.035782e-02 -9.092742e-01  ...  1.975798e-01 -7.310472e-01
50%   -3.035782e-02 -5.546851e-01  ...  1.975798e-01 -1.854849e-01
75%   -3.035782e-02  1.002261e+00  ...  1.975798e-01  9.056397e-01
max    5.713931e+00  1.737069e+00  ...  1.975798e-01  1.996764e+00

[8 rows x 70 columns]

In [13]:
normalized_x=normalized_df.iloc[:,normalized_df.columns != 'Label']

In [14]:
normalized_x.describe()

Source IP   Source Port  ...      Idle Min       Inbound
count  1.245798e+06  1.245798e+06  ...  1.245798e+06  1.245798e+06
mean  -2.874317e-13  1.054733e-12  ... -2.619898e-12 -2.792804e-12
std    1.000000e+00  1.000000e+00  ...  1.000000e+00  1.000000e+00
min   -1.919144e+01 -9.406960e-01  ... -1.817855e-01 -5.061243e+00
25%   -3.035782e-02 -9.092742e-01  ... -1.817855e-01  1.975798e-01
50%   -3.035782e-02 -5.546851e-01  ... -1.817855e-01  1.975798e-01
75%   -3.035782e-02  1.002261e+00  ... -1.817855e-01  1.975798e-01
max    5.713931e+00  1.737069e+00  ...  2.947497e+01  1.975798e-01

[8 rows x 69 columns]

In [15]:
from sklearn.model_selection import train_test_split
import numpy as np
X_train, X_test, y_train, y_test = train_test_split(normalized_x, y, test_size=0.25, random_state=0)
y_train = np.array(y_train)

In [16]:
normalized_x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1245798 entries, 0 to 1245797
Data columns (total 69 columns):
 #   Column                        Non-Null Count    Dtype  
---  ------                        --------------    -----  
 0    Source IP                    1245798 non-null  float64
 1    Source Port                  1245798 non-null  float64
 2    Destination IP               1245798 non-null  float64
 3    Destination Port             1245798 non-null  float64
 4    Protocol                     1245798 non-null  float64
 5    Flow Duration                1245798 non-null  float64
 6    Total Fwd Packets            1245798 non-null  float64
 7    Total Backward Packets       1245798 non-null  float64
 8   Total Length of Fwd Packets   1245798 non-null  float64
 9    Total Length of Bwd Packets  1245798 non-null  float64
 10   Fwd Packet Length Max        1245798 non-null  float64
 11   Fwd Packet Length Min        1245798 non-null  float64
 12   Fwd Packet Length Mean     

In [17]:
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1245798 entries, 0 to 1245797
Data columns (total 1 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   Label   1245798 non-null  int64
dtypes: int64(1)
memory usage: 9.5 MB


In [18]:
#stochastic gradient descent
from  sklearn.linear_model import SGDClassifier, LinearRegression
from sklearn import metrics
lr = SGDClassifier(loss="log", penalty="l2", max_iter=200)
lr.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDClassifier(loss='log', max_iter=200)

In [19]:
y_pred = lr.predict(X_test)
print("Stochastic Gradient Descent\nAccuracy =", metrics.accuracy_score(y_test, y_pred)*100)

Stochastic Gradient Descent
Accuracy = 77.12506020227966


In [20]:
from sklearn import metrics
from sklearn.metrics import f1_score
print('Stochastic Gradient Descent')

print('Accuracy = ', metrics.accuracy_score(y_test, y_pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None, 
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred, 
                                                                 labels=None, 
                                                                 target_names=None, 
                                                                 sample_weight=None, 
                                                                 digits=2, 
                                                                 output_dict=False))

print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

Stochastic Gradient Descent
Accuracy =  77.12506020227966
Confusion Matrix =
 [[14099    15     0     2    54    80    29    42]
 [    0 43034     2     0  6713     2    11     0]
 [    3     9 49202   584    18     5     1     0]
 [    0     1   316 47287   856     0  1814     1]
 [   20 41071     0   119  5557   113    31     7]
 [   40     0     0     4     0 49620     0     0]
 [    2     0     0 18791    14     4 31346    10]
 [   21     0     0   167    63    17   192    61]]
Recall = 0.7712506020227966
Classification Report =
               precision    recall  f1-score   support

           0       0.99      0.98      0.99     14321
           1       0.51      0.86      0.64     49762
           2       0.99      0.99      0.99     49822
           3       0.71      0.94      0.81     50275
           4       0.42      0.12      0.18     46918
           5       1.00      1.00      1.00     49664
           6       0.94      0.62      0.75     50167
           7       0.50    

In [21]:
yt = y_test.iloc[:,0]
yt=np.array(yt)

In [22]:
y_pred[3]

2

In [23]:
y_test = yt
#y_pred = y_pred[:, 0]

In [24]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=8)
model.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=8)

In [25]:
y_pred = model.predict(X_test)
print("Accuracy =", metrics.accuracy_score(y_test, y_pred))

Accuracy = 0.8701011398298282


In [26]:
from sklearn import metrics
from sklearn.metrics import f1_score

print('K Nearest Neighbour Classifier')

print('Accuracy = ', metrics.accuracy_score(y_test, y_pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None, 
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred, 
                                                                 labels=None, 
                                                                 target_names=None, 
                                                                 sample_weight=None, 
                                                                  digits=2, 
                                                                 output_dict=False))
print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

K Nearest Neighbour Classifier
Accuracy =  87.01011398298282
Confusion Matrix =
 [[14310     0     0     0     1    10     0     0]
 [    0 36928     2    13 12818     1     0     0]
 [    3     3 49745    61     7     3     0     0]
 [    1     0    69 48868    26     0  1310     1]
 [   11 24409    11    65 22407     1     6     8]
 [    3     0     0     1     1 49657     2     0]
 [    0     0     0  1229    13     1 48886    38]
 [    3     0     0    15    40     3   268   192]]
Recall = 0.8701011398298282
Classification Report =
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     14321
           1       0.60      0.74      0.66     49762
           2       1.00      1.00      1.00     49822
           3       0.97      0.97      0.97     50275
           4       0.63      0.48      0.54     46918
           5       1.00      1.00      1.00     49664
           6       0.97      0.97      0.97     50167
           7       0.80 

In [27]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [28]:
pred = model.predict(X_test)

In [29]:
from sklearn import metrics
from sklearn.metrics import f1_score

print('Naive Bayes')

print('Accuracy = ', metrics.accuracy_score(y_test, pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None, 
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred, 
                                                                 labels=None, 
                                                                 target_names=None, 
                                                                 sample_weight=None, 
                                                                  digits=2, 
                                                                 output_dict=False))
print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

Naive Bayes
Accuracy =  75.54503130518543
Confusion Matrix =
 [[14310     0     0     0     1    10     0     0]
 [    0 36928     2    13 12818     1     0     0]
 [    3     3 49745    61     7     3     0     0]
 [    1     0    69 48868    26     0  1310     1]
 [   11 24409    11    65 22407     1     6     8]
 [    3     0     0     1     1 49657     2     0]
 [    0     0     0  1229    13     1 48886    38]
 [    3     0     0    15    40     3   268   192]]
Recall = 0.8701011398298282
Classification Report =
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     14321
           1       0.60      0.74      0.66     49762
           2       1.00      1.00      1.00     49822
           3       0.97      0.97      0.97     50275
           4       0.63      0.48      0.54     46918
           5       1.00      1.00      1.00     49664
           6       0.97      0.97      0.97     50167
           7       0.80      0.37      0.51